# Generated by Django 4.1.3 on 2022-11-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя бренда')),
                ('brand', models.CharField(max_length=500, verbose_name='Бренд')),
                ('made_city', models.CharField(max_length=150, verbose_name='Произведено:')),
                ('differences', models.TextField(max_length=500, verbose_name='Отличительные черты')),
                ('description', models.TextField(verbose_name='Описание:')),
                ('price', models.IntegerField(default=0, verbose_name='Цена:')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.category', verbose_name='Категория:')),
            ],
        ),
    ]
